"""Aggiunto saldo a User

Revision ID: e844299dc844
Revises: 
Create Date: 2025-05-11 20:34:26.617398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e844299dc844'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('name', sa.String(), nullable=True))
    op.drop_index('ix_items_title', table_name='items')
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    op.drop_column('items', 'title')
    op.add_column('users', sa.Column('balance', sa.Integer(), nullable=True))
    # op.alter_column('users', 'username',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # op.alter_column('users', 'password',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('users', 'password',
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    # op.alter_column('users', 'username',
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    op.drop_column('users', 'balance')
    op.add_column('items', sa.Column('title', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.create_index('ix_items_title', 'items', ['title'], unique=False)
    op.drop_column('items', 'name')
    # ### end Alembic commands ###
